name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

  pull_request:
    branches: [ main, dev ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      SECRET_KEY: github_actions

    services:
      postgres:
        image: postgres:15.0
        env:
          POSTGRES_DB: github_actions
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install psycopg prerequisites
        run: |
          sudo apt-get install libpq-dev

      - name: Install poetry
        run: |
          python -m pip install --upgrade poetry wheel

      - id: cache-poetry
        uses: actions/cache@v4
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Django tests
        run: |
          poetry run coverage run manage.py test

      - name: Code coverage
        run: |
          poetry run coverage report -m
