name: Frontend Tests

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

  pull_request:
    branches: [main, dev]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: frontend
    env:
      SKIP_ENV_VALIDATION: true

    strategy:
      matrix:
        node: [18, 20]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: "frontend/pnpm-lock.yaml"

      - name: Install dependencies
        run: |
          pnpm install

      - name: Run unit tests
        run: |
          pnpm test
