name: Publish package to GitHub Packages

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'node-package/**'
      - '.github/workflows/node-package-release.yml'

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  REGISTRY_URL: https://npm.pkg.github.com
  SCOPE: '@${{ github.repository_owner }}'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: node-package

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'pnpm'
          cache-dependency-path: 'node-package/pnpm-lock.yaml'
          # Setup .npmrc file to publish to GitHub Packages
          registry-url: ${{ env.REGISTRY_URL }}
          scope: ${{ env.SCOPE }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run ci:publish
          cwd: node-package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
