name: Node Package Tests

on:
  push:
    paths:
      - 'node-package/**'
      - '.github/workflows/node-package.yml'

  pull_request:
    branches: [ main, dev ]
    paths:
      - 'node-package/**'
      - '.github/workflows/node-package.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    defaults:
      run:
        working-directory: node-package

    strategy:
      matrix:
        node: [ 18, 20 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          cache-dependency-path: 'node-package/pnpm-lock.yaml'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests with coverage
        run: pnpm test:coverage
